- name : Create /etc/haproxy/ directory
  file: path=/etc/haproxy state=directory

- name : Install Haproxy
  apt : name=haproxy

- name : Copy haproxy.cfg
  template : >
    src=../files/haproxy.cfg.j2
    dest=/etc/haproxy/haproxy.cfg
    mode=0644
    force=yes
  register: haproxycfg

- name : Restart haproxy
  shell :  /usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg -D -p /var/run/haproxy.pid -sf $(cat /var/run/haproxy.pid)
  when : haproxycfg.changed
