---
# tasks file for myapp
- name: Create myapp log directory
  file: path=/var/log/myapp/ state=directory mode=0755

- name : Install supervisor
  apt : name=supervisor

- name: Get my app jar from repository
  shell: 
    wget https://raw.githubusercontent.com/fabulous-lab/spring-boot-postgres-sample/master/target/myapp-{{myapp_version}}-SNAPSHOT.jar
    chdir=/home/vagrant/ 

- name : Rename myapp jar
  command : mv /home/vagrant/myapp-{{myapp_version}}-SNAPSHOT.jar /home/vagrant/myapp.jar
  
- name : Copy supervisor config file
  copy : src=../files/myapp.conf dest=/etc/supervisor/conf.d/

- name : Start supervisor
  service : name=supervisor state=restarted

- name : Start/Restart myapp
  supervisorctl: name=myapp state=started

- name : Wait myapp start
  wait_for: port=8080 delay=10
